# Use full Python 3.11 image to avoid ML compatibility issues
FROM python:3.11

LABEL maintainer="Mackenzie Rock"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
COPY .env .env
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy ONLY FastAPI-related code
COPY . /app/wildfire_1


# Expose the port that Cloud Run will map
EXPOSE 8000

# Run FastAPI and bind to the port Cloud Run provides
CMD ["bash", "-c", "uvicorn wildfire_1.app.main:app --host 0.0.0.0 --port $PORT"]
